spring.application.name=database-institute
spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres?pgbouncer=true
spring.datasource.username=postgres.database-institute
spring.datasource.password=spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update